version: '3.7'

services:
  frontend:
    container_name: FRONTEND
    build:
      context: ./frontend
    volumes:
      - './frontend/modern/node_modules:/app/modern/node_modules/'
      - './frontend/modern/:/app/modern/'
    ports:
      - 3001:3000
    restart: always
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - server
    network_mode: host

  server:
    container_name: GEONTRACK_SERVER
    build:
      context: '.'
    ports:
      - 8082:8082
    restart: always
    network_mode: host

networks: 
  linker:
